name: Continuous integration - private registry
permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  test-net-private:
    name: Test Suite (network-enabled tests)
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.85.0"  # MSRV
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ matrix.rust }}

      # - name: Run cargo test (test-net-private)
      #   run: cargo test --features test-net,test-net-private
      #   env:
      #     DOCKER_REGISTRY_QUAY_USER: ${{ secrets.DOCKER_REGISTRY_QUAY_USER }}
      #     DOCKER_REGISTRY_QUAY_PASSWD: ${{ secrets.DOCKER_REGISTRY_QUAY_PASSWD }}
